version: '3'

services:
  express-services:
    container_name: Turo

    build: .

    volumes: 
      - ./:/app:Z

    ports:
      - "8001:8001"

    command: ["node", "express.js"]

  postgres-db-turo:
      container_name: postgres-db-turo
      image: postgres:latest
      restart: always
      environment:
        DATABASE_HOST: postgres-db-turo
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_PORT: 5432
        POSTGRES_DB: Turo_webpage
      ports:
        - "5432:5432"
      volumes:
          # copy the sql script to create tables
            - ./migrate_seed/db/migrate.sql:/docker-entrypoint-initdb.d/migrate.sql
            - ./migrate_seed/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql


  pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgAdmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: burmanbed@gmail.com
            PGADMIN_DEFAULT_PASSWORD: password
        ports:
            - "8080:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - postgres-db-turo

volumes:
  pgadmin-data: