version: '3'

services:
#   express-services:
#     container_name: SDC-Turo

#     build: .

#     volumes: 
#       - ./:/app:Z

#     ports:
#       - "8100:8100"

#     command: ["node", "express.js"]

  # k6:
  #   image: loadimpact/k6
  #   volumes:
  #     - ./tests:/tests
  #   command: ["run", "Back-End-test/test.js"]
# #   command: run --vus 10 --duration 30s /path/to/script.js

  # redis:
  #   container_name: SDC-redis
  #   image: redis/redis-stack:latest
  #   environment:
  #     # ALLOW_EMPTY_PASSWORD is recommended only for development.
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  #   ports:
  #     - 8001:6379
  #   restart: always
  #   entrypoint: redis-server --appendonly yes
  

  SDC-postgres-db-turo:
      container_name: SDC-postgres-db-turo
      image: postgres:latest
      restart: always
      environment:
        DATABASE_HOST: 127.0.0.1
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_PORT: 5432
        POSTGRES_DB: SDC
      ports:
        - "5432:5432"
      volumes:
          # copy the sql script to create tables
            - ./Database/migrate.sql:/docker-entrypoint-initdb.d/migrate.sql
            - ./Database/seed.sql:/docker-entrypoint-initdb.d/seed.sql


  # pgadmin:
  #       image: dpage/pgadmin4:latest
  #       container_name: pgAdmin
  #       restart: always
  #       environment:
  #           PGADMIN_DEFAULT_EMAIL: jasmith0401@gmail.com
  #           PGADMIN_DEFAULT_PASSWORD: password
  #       ports:
  #           - "8080:80"
  #       volumes:
  #           - pgadmin-data:/var/lib/pgadmin
  #       depends_on:
  #           - SDC-postgres-db-turo

# volumes:
#   pgadmin-data: